# Copia .env.example a .env en la raíz del proyecto y define DATABASE_URL (y las demás variables necesarias).

services:
  # Tu Backend FastAPI
  backend:
    build:
      context: "./"
      dockerfile: Dockerfile
    container_name: calofit_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
