"""sincronizar esquema completo con modelos actuales

Revision ID: a3f7c9d81b44
Revises: d07b43e35f9a
Create Date: 2026-09-22 01:10:00.000000

Reemplaza la cadena de migraciones posterior a d07b43e35f9a, que estaba
incompleta (le faltaban ~15 tablas que solo existian via Base.metadata.create_all)
y tenia varios historiales rotos (heads divergentes, tipos de SQLite colados
en migraciones para Postgres, orden de creacion que violaba FKs). Generada
comparando una BD limpia (con el historial hasta d07b43e35f9a aplicado)
contra los modelos actuales de SQLAlchemy.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a3f7c9d81b44'
down_revision: Union[str, Sequence[str], None] = 'd07b43e35f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('nombre_normalizado', sa.String(length=255), nullable=False),
    sa.Column('calorias_100g', sa.Float(), nullable=False),
    sa.Column('proteina_100g', sa.Float(), nullable=False),
    sa.Column('carbohidratos_100g', sa.Float(), nullable=False),
    sa.Column('grasas_100g', sa.Float(), nullable=False),
    sa.Column('fibra_100g', sa.Float(), nullable=True),
    sa.Column('azucar_100g', sa.Float(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('fuente', sa.String(length=255), nullable=True),
    sa.Column('id_externo', sa.String(length=100), nullable=True),
    sa.Column('es_confiable', sa.Boolean(), nullable=True),
    sa.Column('pendiente_validacion', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alimentos_id'), 'alimentos', ['id'], unique=False)
    op.create_index(op.f('ix_alimentos_nombre'), 'alimentos', ['nombre'], unique=True)
    op.create_index(op.f('ix_alimentos_nombre_normalizado'), 'alimentos', ['nombre_normalizado'], unique=False)
    op.create_table('ejercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('nombre_normalizado', sa.String(length=255), nullable=False),
    sa.Column('alias', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('met', sa.Float(), nullable=False),
    sa.Column('grupo_muscular', sa.String(length=128), nullable=True),
    sa.Column('origen', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ejercicios_id'), 'ejercicios', ['id'], unique=False)
    op.create_index(op.f('ix_ejercicios_nombre'), 'ejercicios', ['nombre'], unique=False)
    op.create_index(op.f('ix_ejercicios_nombre_normalizado'), 'ejercicios', ['nombre_normalizado'], unique=False)
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('reset_code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_resets_id'), 'password_resets', ['id'], unique=False)
    op.create_table('platos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('nombre_normalizado', sa.String(length=255), nullable=False),
    sa.Column('tipo_plato', sa.String(length=50), nullable=True),
    sa.Column('budget_level', sa.String(length=20), nullable=True),
    sa.Column('meal_style', sa.String(length=50), nullable=True),
    sa.Column('preparacion', sa.JSON(), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('origen', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platos_id'), 'platos', ['id'], unique=False)
    op.create_index(op.f('ix_platos_nombre_normalizado'), 'platos', ['nombre_normalizado'], unique=True)
    op.create_table('rutinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('perfil_tipo', sa.String(length=16), nullable=True),
    sa.Column('nivel', sa.String(length=32), nullable=True),
    sa.Column('grupo_muscular', sa.String(length=128), nullable=True),
    sa.Column('tiempo_min', sa.Integer(), nullable=True),
    sa.Column('series_config', sa.Text(), nullable=True),
    sa.Column('origen', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rutinas_grupo_muscular'), 'rutinas', ['grupo_muscular'], unique=False)
    op.create_index(op.f('ix_rutinas_id'), 'rutinas', ['id'], unique=False)
    op.create_index(op.f('ix_rutinas_perfil_tipo'), 'rutinas', ['perfil_tipo'], unique=False)
    op.create_table('alimento_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alimento_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('alias_normalizado', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['alimento_id'], ['alimentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alimento_alias_alias_normalizado'), 'alimento_alias', ['alias_normalizado'], unique=False)
    op.create_index(op.f('ix_alimento_alias_id'), 'alimento_alias', ['id'], unique=False)
    op.create_table('alimento_unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alimento_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('gramos', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['alimento_id'], ['alimentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alimento_unidades_id'), 'alimento_unidades', ['id'], unique=False)
    op.create_table('app_cache_alimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_normalized', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('alimento_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alimento_id'], ['alimentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cache_expires', 'app_cache_alimentos', ['expires_at'], unique=False)
    op.create_index('idx_cache_food', 'app_cache_alimentos', ['food_normalized'], unique=False)
    op.create_index(op.f('ix_app_cache_alimentos_food_normalized'), 'app_cache_alimentos', ['food_normalized'], unique=False)
    op.create_index(op.f('ix_app_cache_alimentos_id'), 'app_cache_alimentos', ['id'], unique=False)
    op.create_index(op.f('ix_app_cache_alimentos_user_id'), 'app_cache_alimentos', ['user_id'], unique=False)
    op.create_table('app_cache_platos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plato_normalized', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('plato_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plato_id'], ['platos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cache_plato_expires', 'app_cache_platos', ['expires_at'], unique=False)
    op.create_index('idx_cache_plato_norm', 'app_cache_platos', ['plato_normalized'], unique=False)
    op.create_index(op.f('ix_app_cache_platos_id'), 'app_cache_platos', ['id'], unique=False)
    op.create_index(op.f('ix_app_cache_platos_plato_normalized'), 'app_cache_platos', ['plato_normalized'], unique=False)
    op.create_index(op.f('ix_app_cache_platos_user_id'), 'app_cache_platos', ['user_id'], unique=False)
    op.create_table('app_cache_rutinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('perfil_tipo', sa.String(length=16), nullable=True),
    sa.Column('zonas_objetivo', sa.Text(), nullable=True),
    sa.Column('tiempo_min', sa.Integer(), nullable=True),
    sa.Column('rutina_json', sa.Text(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cache_rutinas_expires', 'app_cache_rutinas', ['expires_at'], unique=False)
    op.create_index(op.f('ix_app_cache_rutinas_cache_key'), 'app_cache_rutinas', ['cache_key'], unique=True)
    op.create_index(op.f('ix_app_cache_rutinas_id'), 'app_cache_rutinas', ['id'], unique=False)
    op.create_index(op.f('ix_app_cache_rutinas_user_id'), 'app_cache_rutinas', ['user_id'], unique=False)
    op.create_table('comida_registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('nombre_alimento', sa.String(length=255), nullable=False),
    sa.Column('plato_id', sa.Integer(), nullable=True),
    sa.Column('alimento_id', sa.Integer(), nullable=True),
    sa.Column('gramos', sa.Float(), nullable=True),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('proteina_g', sa.Float(), nullable=False),
    sa.Column('carbohidratos_g', sa.Float(), nullable=False),
    sa.Column('grasas_g', sa.Float(), nullable=False),
    sa.Column('tipo_resolucion', sa.String(length=50), nullable=False),
    sa.Column('confianza', sa.Float(), nullable=False),
    sa.Column('texto_original', sa.String(length=500), nullable=True),
    sa.Column('momento', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alimento_id'], ['alimentos.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['plato_id'], ['platos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comida_registros_client_id'), 'comida_registros', ['client_id'], unique=False)
    op.create_index(op.f('ix_comida_registros_fecha'), 'comida_registros', ['fecha'], unique=False)
    op.create_index(op.f('ix_comida_registros_id'), 'comida_registros', ['id'], unique=False)
    op.create_table('historial_imc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('imc', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_imc_id'), 'historial_imc', ['id'], unique=False)
    op.create_table('historial_peso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_peso_id'), 'historial_peso', ['id'], unique=False)
    op.create_table('historial_recomendaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('plato_id', sa.Integer(), nullable=True),
    sa.Column('nombre_plato', sa.String(length=255), nullable=True),
    sa.Column('calorias', sa.Float(), nullable=True),
    sa.Column('proteinas_g', sa.Float(), nullable=True),
    sa.Column('carbohidratos_g', sa.Float(), nullable=True),
    sa.Column('grasas_g', sa.Float(), nullable=True),
    sa.Column('momento_dia', sa.String(length=30), nullable=True),
    sa.Column('fue_consumido', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plato_id'], ['platos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_recomendaciones_client_id'), 'historial_recomendaciones', ['client_id'], unique=False)
    op.create_index(op.f('ix_historial_recomendaciones_id'), 'historial_recomendaciones', ['id'], unique=False)
    op.create_index(op.f('ix_historial_recomendaciones_plato_id'), 'historial_recomendaciones', ['plato_id'], unique=False)
    op.create_table('metas_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=1), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=False),
    sa.Column('talla_cm', sa.Float(), nullable=False),
    sa.Column('nivel_actividad', sa.String(length=32), nullable=False),
    sa.Column('objetivo', sa.String(length=64), nullable=False),
    sa.Column('tmb', sa.Float(), nullable=False),
    sa.Column('get', sa.Float(), nullable=False),
    sa.Column('calorias_objetivo', sa.Float(), nullable=False),
    sa.Column('proteinas_g', sa.Float(), nullable=False),
    sa.Column('carbohidratos_g', sa.Float(), nullable=False),
    sa.Column('grasas_g', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metas_usuario_id'), 'metas_usuario', ['id'], unique=False)
    op.create_table('plato_ingredientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plato_id', sa.Integer(), nullable=False),
    sa.Column('alimento_id', sa.Integer(), nullable=False),
    sa.Column('gramos', sa.Float(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('notas', sa.String(length=255), nullable=True),
    sa.CheckConstraint('gramos > 0', name='ck_plato_ing_gramos_positivo'),
    sa.ForeignKeyConstraint(['alimento_id'], ['alimentos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plato_id'], ['platos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plato_ingredientes_id'), 'plato_ingredientes', ['id'], unique=False)
    op.create_index(op.f('ix_plato_ingredientes_plato_id'), 'plato_ingredientes', ['plato_id'], unique=False)
    op.create_table('preferencias_alimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('alimento', sa.String(length=200), nullable=False),
    sa.Column('frecuencia', sa.Integer(), nullable=True),
    sa.Column('puntuacion', sa.Float(), nullable=True),
    sa.Column('calorias', sa.Float(), nullable=True),
    sa.Column('proteinas', sa.Float(), nullable=True),
    sa.Column('carbohidratos', sa.Float(), nullable=True),
    sa.Column('grasas', sa.Float(), nullable=True),
    sa.Column('ultima_vez', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preferencias_alimentos_id'), 'preferencias_alimentos', ['id'], unique=False)
    op.create_table('preferencias_ejercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('ejercicio', sa.String(length=200), nullable=False),
    sa.Column('frecuencia', sa.Integer(), nullable=True),
    sa.Column('puntuacion', sa.Float(), nullable=True),
    sa.Column('calorias_quemadas', sa.Float(), nullable=True),
    sa.Column('ultima_vez', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preferencias_ejercicios_id'), 'preferencias_ejercicios', ['id'], unique=False)
    op.create_table('progreso_calorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('calorias_consumidas', sa.Integer(), nullable=True),
    sa.Column('calorias_quemadas', sa.Integer(), nullable=False),
    sa.Column('proteinas_consumidas', sa.Float(), nullable=True),
    sa.Column('carbohidratos_consumidos', sa.Float(), nullable=True),
    sa.Column('grasas_consumidas', sa.Float(), nullable=True),
    sa.Column('deficit_superavit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progreso_calorias_id'), 'progreso_calorias', ['id'], unique=False)
    op.create_table('rutinas_ejercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rutina_id', sa.Integer(), nullable=False),
    sa.Column('ejercicio_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('descanso_s', sa.Integer(), nullable=False),
    sa.Column('peso_sugerido_kg', sa.Float(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutinas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rut_ej_orden', 'rutinas_ejercicios', ['rutina_id', 'orden'], unique=False)
    op.create_index(op.f('ix_rutinas_ejercicios_ejercicio_id'), 'rutinas_ejercicios', ['ejercicio_id'], unique=False)
    op.create_index(op.f('ix_rutinas_ejercicios_id'), 'rutinas_ejercicios', ['id'], unique=False)
    op.create_index(op.f('ix_rutinas_ejercicios_rutina_id'), 'rutinas_ejercicios', ['rutina_id'], unique=False)
    op.create_table('sugerencias_guardadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('ingredientes', sa.JSON(), nullable=True),
    sa.Column('preparacion', sa.JSON(), nullable=True),
    sa.Column('macros', sa.String(length=255), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.Column('fecha_guardado', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sugerencias_guardadas_id'), 'sugerencias_guardadas', ['id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('rutina_id', sa.Integer(), nullable=True),
    sa.Column('nombre_rutina', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('duracion_min', sa.Integer(), nullable=True),
    sa.Column('calorias_quemadas', sa.Float(), nullable=True),
    sa.Column('intensity', sa.String(length=16), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutinas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ws_client_fecha', 'workout_sessions', ['client_id', 'fecha'], unique=False)
    op.create_index(op.f('ix_workout_sessions_client_id'), 'workout_sessions', ['client_id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_fecha'), 'workout_sessions', ['fecha'], unique=False)
    op.create_index(op.f('ix_workout_sessions_id'), 'workout_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_rutina_id'), 'workout_sessions', ['rutina_id'], unique=False)
    op.create_table('alertas_salud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('severidad', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('atendido_por_id', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_deteccion', sa.TIMESTAMP(), nullable=False),
    sa.Column('fecha_atencion', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['atendido_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_salud_id'), 'alertas_salud', ['id'], unique=False)
    op.create_table('alimentos_sin_resolver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_original', sa.String(length=512), nullable=False),
    sa.Column('nombre_normalizado', sa.String(length=512), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('mensaje_contexto', sa.Text(), nullable=True),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=32), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_reporte', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado IN ('pendiente', 'validado', 'rechazado')", name='ck_alimento_sin_resolver_estado'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alimentos_sin_resolver_estado'), 'alimentos_sin_resolver', ['estado'], unique=False)
    op.create_index(op.f('ix_alimentos_sin_resolver_id'), 'alimentos_sin_resolver', ['id'], unique=False)
    op.create_index(op.f('ix_alimentos_sin_resolver_nombre_normalizado'), 'alimentos_sin_resolver', ['nombre_normalizado'], unique=False)
    op.create_index(op.f('ix_alimentos_sin_resolver_user_id'), 'alimentos_sin_resolver', ['user_id'], unique=False)
    op.create_table('auditoria_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=50), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('fecha_evento', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_admin_id'), 'auditoria_admin', ['id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=True),
    sa.Column('validado_por_id', sa.Integer(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('concepto', sa.String(length=200), nullable=True),
    sa.Column('comprobante_url', sa.String(), nullable=True),
    sa.Column('notas_admin', sa.Text(), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('fecha_validacion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['validado_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_client_id'), 'pagos', ['client_id'], unique=False)
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    op.create_table('workout_session_ejercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('ejercicio_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('series_completadas', sa.Integer(), nullable=True),
    sa.Column('reps_completadas', sa.Integer(), nullable=True),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('duracion_s', sa.Integer(), nullable=True),
    sa.Column('calorias_quemadas', sa.Float(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wse_session_orden', 'workout_session_ejercicios', ['session_id', 'orden'], unique=False)
    op.create_index(op.f('ix_workout_session_ejercicios_ejercicio_id'), 'workout_session_ejercicios', ['ejercicio_id'], unique=False)
    op.create_index(op.f('ix_workout_session_ejercicios_id'), 'workout_session_ejercicios', ['id'], unique=False)
    op.create_index(op.f('ix_workout_session_ejercicios_session_id'), 'workout_session_ejercicios', ['session_id'], unique=False)
    op.add_column('clients', sa.Column('dni', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('clients', sa.Column('gender', sa.String(length=1), nullable=False))
    op.add_column('clients', sa.Column('activity_level', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('goal', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('workout_type', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('session_duration', sa.Float(), nullable=True))
    op.add_column('clients', sa.Column('meal_reminder_time', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('recommended_foods', postgresql.ARRAY(String()), nullable=True))
    op.add_column('clients', sa.Column('forbidden_foods', postgresql.ARRAY(String()), nullable=True))
    op.add_column('clients', sa.Column('ai_strategic_focus', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('profile_picture_url', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('is_profile_complete', sa.Boolean(), nullable=True))
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('clients', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('verification_code', sa.String(length=6), nullable=True))
    op.add_column('clients', sa.Column('code_expires_at', sa.DateTime(), nullable=True))
    op.alter_column('clients', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'last_name_paternal',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'last_name_maternal',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('clients', 'medical_conditions')
    op.add_column('clients', sa.Column('medical_conditions', postgresql.ARRAY(String()), nullable=True))
    op.create_index(op.f('ix_clients_dni'), 'clients', ['dni'], unique=True)
    op.drop_constraint('clients_assigned_coach_id_fkey', 'clients', type_='foreignkey')
    op.drop_constraint('clients_assigned_nutri_id_fkey', 'clients', type_='foreignkey')
    op.drop_column('clients', 'age')
    op.drop_column('clients', 'assigned_coach_id')
    op.drop_column('clients', 'assigned_nutri_id')
    op.add_column('planes_diarios', sa.Column('comidas', sa.JSON(), nullable=True))
    op.add_column('planes_nutricionales', sa.Column('status', sa.String(), nullable=True))
    op.add_column('planes_nutricionales', sa.Column('validated_by_id', sa.Integer(), nullable=True))
    op.add_column('planes_nutricionales', sa.Column('validated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key('fk_planes_nutricionales_validated_by_id_users', 'planes_nutricionales', 'users', ['validated_by_id'], ['id'])
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'is_active')
    op.drop_constraint('fk_planes_nutricionales_validated_by_id_users', 'planes_nutricionales', type_='foreignkey')
    op.drop_column('planes_nutricionales', 'validated_at')
    op.drop_column('planes_nutricionales', 'validated_by_id')
    op.drop_column('planes_nutricionales', 'status')
    op.drop_column('planes_diarios', 'comidas')
    op.add_column('clients', sa.Column('assigned_nutri_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('assigned_coach_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('clients_assigned_nutri_id_fkey', 'clients', 'users', ['assigned_nutri_id'], ['id'])
    op.create_foreign_key('clients_assigned_coach_id_fkey', 'clients', 'users', ['assigned_coach_id'], ['id'])
    op.drop_index(op.f('ix_clients_dni'), table_name='clients')
    op.drop_column('clients', 'medical_conditions')
    op.add_column('clients', sa.Column('medical_conditions', sa.TEXT(), nullable=True))
    op.alter_column('clients', 'last_name_maternal',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'last_name_paternal',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('clients', 'code_expires_at')
    op.drop_column('clients', 'verification_code')
    op.drop_column('clients', 'phone')
    op.drop_column('clients', 'is_active')
    op.drop_column('clients', 'is_profile_complete')
    op.drop_column('clients', 'profile_picture_url')
    op.drop_column('clients', 'ai_strategic_focus')
    op.drop_column('clients', 'forbidden_foods')
    op.drop_column('clients', 'recommended_foods')
    op.drop_column('clients', 'meal_reminder_time')
    op.drop_column('clients', 'session_duration')
    op.drop_column('clients', 'workout_type')
    op.drop_column('clients', 'goal')
    op.drop_column('clients', 'activity_level')
    op.drop_column('clients', 'gender')
    op.drop_column('clients', 'birth_date')
    op.drop_column('clients', 'dni')
    op.drop_index(op.f('ix_workout_session_ejercicios_session_id'), table_name='workout_session_ejercicios')
    op.drop_index(op.f('ix_workout_session_ejercicios_id'), table_name='workout_session_ejercicios')
    op.drop_index(op.f('ix_workout_session_ejercicios_ejercicio_id'), table_name='workout_session_ejercicios')
    op.drop_index('idx_wse_session_orden', table_name='workout_session_ejercicios')
    op.drop_table('workout_session_ejercicios')
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_client_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_auditoria_admin_id'), table_name='auditoria_admin')
    op.drop_table('auditoria_admin')
    op.drop_index(op.f('ix_alimentos_sin_resolver_user_id'), table_name='alimentos_sin_resolver')
    op.drop_index(op.f('ix_alimentos_sin_resolver_nombre_normalizado'), table_name='alimentos_sin_resolver')
    op.drop_index(op.f('ix_alimentos_sin_resolver_id'), table_name='alimentos_sin_resolver')
    op.drop_index(op.f('ix_alimentos_sin_resolver_estado'), table_name='alimentos_sin_resolver')
    op.drop_table('alimentos_sin_resolver')
    op.drop_index(op.f('ix_alertas_salud_id'), table_name='alertas_salud')
    op.drop_table('alertas_salud')
    op.drop_index(op.f('ix_workout_sessions_rutina_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_fecha'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_client_id'), table_name='workout_sessions')
    op.drop_index('idx_ws_client_fecha', table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_sugerencias_guardadas_id'), table_name='sugerencias_guardadas')
    op.drop_table('sugerencias_guardadas')
    op.drop_index(op.f('ix_rutinas_ejercicios_rutina_id'), table_name='rutinas_ejercicios')
    op.drop_index(op.f('ix_rutinas_ejercicios_id'), table_name='rutinas_ejercicios')
    op.drop_index(op.f('ix_rutinas_ejercicios_ejercicio_id'), table_name='rutinas_ejercicios')
    op.drop_index('idx_rut_ej_orden', table_name='rutinas_ejercicios')
    op.drop_table('rutinas_ejercicios')
    op.drop_index(op.f('ix_progreso_calorias_id'), table_name='progreso_calorias')
    op.drop_table('progreso_calorias')
    op.drop_index(op.f('ix_preferencias_ejercicios_id'), table_name='preferencias_ejercicios')
    op.drop_table('preferencias_ejercicios')
    op.drop_index(op.f('ix_preferencias_alimentos_id'), table_name='preferencias_alimentos')
    op.drop_table('preferencias_alimentos')
    op.drop_index(op.f('ix_plato_ingredientes_plato_id'), table_name='plato_ingredientes')
    op.drop_index(op.f('ix_plato_ingredientes_id'), table_name='plato_ingredientes')
    op.drop_table('plato_ingredientes')
    op.drop_index(op.f('ix_metas_usuario_id'), table_name='metas_usuario')
    op.drop_table('metas_usuario')
    op.drop_index(op.f('ix_historial_recomendaciones_plato_id'), table_name='historial_recomendaciones')
    op.drop_index(op.f('ix_historial_recomendaciones_id'), table_name='historial_recomendaciones')
    op.drop_index(op.f('ix_historial_recomendaciones_client_id'), table_name='historial_recomendaciones')
    op.drop_table('historial_recomendaciones')
    op.drop_index(op.f('ix_historial_peso_id'), table_name='historial_peso')
    op.drop_table('historial_peso')
    op.drop_index(op.f('ix_historial_imc_id'), table_name='historial_imc')
    op.drop_table('historial_imc')
    op.drop_index(op.f('ix_comida_registros_id'), table_name='comida_registros')
    op.drop_index(op.f('ix_comida_registros_fecha'), table_name='comida_registros')
    op.drop_index(op.f('ix_comida_registros_client_id'), table_name='comida_registros')
    op.drop_table('comida_registros')
    op.drop_index(op.f('ix_app_cache_rutinas_user_id'), table_name='app_cache_rutinas')
    op.drop_index(op.f('ix_app_cache_rutinas_id'), table_name='app_cache_rutinas')
    op.drop_index(op.f('ix_app_cache_rutinas_cache_key'), table_name='app_cache_rutinas')
    op.drop_index('idx_cache_rutinas_expires', table_name='app_cache_rutinas')
    op.drop_table('app_cache_rutinas')
    op.drop_index(op.f('ix_app_cache_platos_user_id'), table_name='app_cache_platos')
    op.drop_index(op.f('ix_app_cache_platos_plato_normalized'), table_name='app_cache_platos')
    op.drop_index(op.f('ix_app_cache_platos_id'), table_name='app_cache_platos')
    op.drop_index('idx_cache_plato_norm', table_name='app_cache_platos')
    op.drop_index('idx_cache_plato_expires', table_name='app_cache_platos')
    op.drop_table('app_cache_platos')
    op.drop_index(op.f('ix_app_cache_alimentos_user_id'), table_name='app_cache_alimentos')
    op.drop_index(op.f('ix_app_cache_alimentos_id'), table_name='app_cache_alimentos')
    op.drop_index(op.f('ix_app_cache_alimentos_food_normalized'), table_name='app_cache_alimentos')
    op.drop_index('idx_cache_food', table_name='app_cache_alimentos')
    op.drop_index('idx_cache_expires', table_name='app_cache_alimentos')
    op.drop_table('app_cache_alimentos')
    op.drop_index(op.f('ix_alimento_unidades_id'), table_name='alimento_unidades')
    op.drop_table('alimento_unidades')
    op.drop_index(op.f('ix_alimento_alias_id'), table_name='alimento_alias')
    op.drop_index(op.f('ix_alimento_alias_alias_normalizado'), table_name='alimento_alias')
    op.drop_table('alimento_alias')
    op.drop_index(op.f('ix_rutinas_perfil_tipo'), table_name='rutinas')
    op.drop_index(op.f('ix_rutinas_id'), table_name='rutinas')
    op.drop_index(op.f('ix_rutinas_grupo_muscular'), table_name='rutinas')
    op.drop_table('rutinas')
    op.drop_index(op.f('ix_platos_nombre_normalizado'), table_name='platos')
    op.drop_index(op.f('ix_platos_id'), table_name='platos')
    op.drop_table('platos')
    op.drop_index(op.f('ix_password_resets_id'), table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index(op.f('ix_ejercicios_nombre_normalizado'), table_name='ejercicios')
    op.drop_index(op.f('ix_ejercicios_nombre'), table_name='ejercicios')
    op.drop_index(op.f('ix_ejercicios_id'), table_name='ejercicios')
    op.drop_table('ejercicios')
    op.drop_index(op.f('ix_alimentos_nombre_normalizado'), table_name='alimentos')
    op.drop_index(op.f('ix_alimentos_nombre'), table_name='alimentos')
    op.drop_index(op.f('ix_alimentos_id'), table_name='alimentos')
    op.drop_table('alimentos')
    # ### end Alembic commands ###
